== Changelog for the TameMyCerts Policy Module

=== 1.5.760.827 (Jan 31, 2023)

This is a quality improvement only release. TameMyCerts now uses the interfaces provided by the certification authority to determine Subject and Subject Alternative Name information.

* Fix a security vulnerability causing nested certificate requests to bypass subject alternative name rule processing. *All users of previous versions are urged to upgrade!*
* Subject RDN inspection is now done against the properties constructed by the certification authority (how the CA would issue the certificate. Previously it was done against the original inline PKCS#10 certificate request). This should enhance compatibility with malformed certificate requests but does not work with undefined relative distinguished names. Behavior can be changed back to previous logic by setting _ReadSubjectFromRequest_ to true in request policy.
* Enhance logging for directory service query failures.
* Refactor the code for building the security identifier certificate extension.

=== 1.4.728.502 (Dec 30, 2022)

This is a quality improvement only release. TameMyCerts is now covered by link:TameMyCerts.IntegrationTests[automated integration tests^] featuring Pester and link:https://github.com/Sleepw4lker/PSCertificateEnrollment[PSCertificateEnrollment^] which allows to test parts of the code base not testable with unit tests.

* Fix a bug causing directory mapping not finding all of mapped object's attributes when using global catalog (no SearchRoot configured in policy) to find an object.
* Fix a bug causing to not display the correct error message in case no connection to Active Directory is possible during directory validation.
* Fix a bug causing certificate modifications made by TameMyCerts are not applied when a template is configured to put requests in pending state.
* Fix a bug causing to falsely log that a certificate request would get denied even if there is no reason to when policy is configured in audit mode.
* Fix a bug causing the StartDate request attribute not getting applied if no policy is configured for the given certificate template.
* Fix a bug causing request attributes to get processed case-sensitive which would allow cirvumventing security measures.
* Fix a bug causing directory mapping to fail when the userPrincipalName attribute is not populated for an account (even if is was not used for mapping). Due to this, mapped accounts are now identified and logged with their distinguishedName attribute instead oder userPrincipalName.
* Fix a bug causing an exception with directory mapping when the telexNumber directory attribute is populated for an object, as the property is not of string data type. Support for the telexNumber directory attribute has therefore been dropped.
* Fix a bug causing requests using a valid process name to get denied when only DisallowedProcesses is configured.
* Fix a bug causing requests using a valid cryptographic provider to get denied when only DisallowedCryptoProviders is configured.
* Attributes used for modification of a certificate's subject distinguished name are now only retrieved from AD if the feature is enabled for a certificate template.

=== 1.3.683.747 (Nov 15, 2022)

* Implement support for (over)writing the subject relative distinguished name (RDN) of issued certificates with configurable attributes from a mapped Active Directory object.
* Implement support for supplementing missing DNS names and IP addresses from commonName field in subject distringushed name into the subject alternative name of the issued certificate. This is to automatically make issued certificates compliant to link:https://www.rfc-editor.org/rfc/rfc2818[RFC 2818^].
* Add option to issue certificates for mapped acounts that are disabled (e.g. to prestage certificates in combination with the "StartDate" attribute functionality).
* Add option to remove Security Identifier (szOID_NTDS_CA_SECURITY_EXT) certificate extension when provided in a certificate request instead of denying it entirely ("Remove" keyword for the SecurityIdentifierExtension directive).
* Key rules can now also be applied to requests for online certificate templates.
* Fix string substitution for the "serialNumber", "unstructuredName" and "unstructuredAddress" relative distinguished name types.
* Fix a bug preventing the use of the "any" IPv4 CIDR mask (0.0.0.0/0) in a subject rule.
* Fix a bug in installer script not updating policy directory.

=== 1.2.587.662 (Aug 11, 2022)

* Implement support for looking up identities that are requested in offline templates against Active Directory (called "directory mapping"). It may be specified if a certificate request shall get denied if a matching user or computer account does not exist, is disabled, if it is member of a forbidden group, or not member of any permitted group.
* Implement support for adding the new Security Identifier (szOID_NTDS_CA_SECURITY_EXT with object id 1.3.6.1.4.1.311.25.2) certificate extension that was introduced with link:https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16[KB5014754^] to certificates issued for offline certificate requests (requires directory mapping). This should enable users to prevent authentication to fail when strong certificate mapping will be enforced on May 9, 2023.
* Implement protection against forgery of the szOID_NTDS_CA_SECURITY_EXT certificate extension by the enrollee. Policy can be configured to deny or allow offline requests containing this extension (default is to deny).
* Implement support for specifying a fixed expiration date on a per-template basis.
* Implement proper logging for processing of the "StartDate" request attribute and align behavior with Windows Default policy module.
* Fix a bug causing the module to return the validation result too early. This had no effect on security but not all violations against the ruleset would get logged, making troubleshooting somewhat more difficult.
* Fix a bug causing the module to throw an exception in the case a SAN extension could not be parsed.
* Fix the organizationalUnitName RDN to align with X.520 specifications (it was wrongly called "organizationalUnit" in earlier versions). *Note that this breaks existing policy files. These must be adjusted.*
* Remove code for denying certificate requests containing the Subject Directory Atttributes (2.5.29.9) request extension, as this is disabled for issuance on AD CS by default anyway.
* Remove excessive calling of garbage collection which should improve processing performance.

=== 1.1.432.1215 (Mar 10, 2022)

* Change logic for allowed and disallowed patterns on SubjectRule directives. Now, for each defined "field" it is possible to specify how the expression will get treated (regular expression or CIDR notation), which allows for IP addresses to get verified if they are present in fields other that the iPAddress alternative name field. *Note that this breaks existing policy files. These must be adjusted.*
* Implement support for applying rules on process names used to create certificate requests for both online and offline certificate templates.
* Implement support for applying rules on cryptographic providers used to create certificate requests' private keys for both online and offline certificate templates.
* Implement support for custom NotBefore date on a certificate with the "StartDate" request attribute, in analogy to the "ExpirationDate" request attribute supported by the Windows Default policy module.
* Implement basic protection against abuse of having the link:https://www.gradenegger.eu/?p=1486[EDITF_ATTRIBUTESUBJECTALTNAME2^] flag enabled. Requests with a "san" attribute get denied if the flag is enabled.
* Fix a bug causing the module to log an exception for requests with invalid "ExpirationDate" attribute.
* SubjectRule "Field" definition is now processed case insensitive.
* Change required link:https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-7-2-offline-installer-for-windows-05a72734-2127-a15d-50cf-daf56d5faec2[.NET Framework 4.7.2^] due to link:https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework[end of life^] of previously used version 4.6.
* General code optimization that should slightly increase processing performance and overall maintainability of the code.
* install.ps1 is now also digitally signed.

=== 1.0.410.1186 (Feb 15, 2022)

_Initial release_