= The "Tame My Certs" policy module for Active Directory Certificate Services

NOTE: Please download the binary package from the link:https://github.com/Sleepw4lker/TameMyCerts/releases[releases page].

NOTE: Please consult the link:CHANGELOG.adoc[Change Log] if upgrading from a previous version.

TameMyCerts is a link:https://docs.microsoft.com/en-us/windows/win32/seccrypto/certificate-services-architecture[policy module^] for Microsoft link:https://docs.microsoft.com/en-us/windows/win32/seccrypto/certificate-services[Active Directory Certificate Services (AD CS)^] enterprise certification authorities, written in C#, that enables security automation for a lot of use cases in the PKI field.

It shims the Windows Default policy module, that means it has the same functionality as the original one, but implements additional checks. This approach was adopted from an link:https://github.com/Sleepw4lker/capolmod[old C++ code sample that initially was published on Codeplex^].

The module supports, amongst other functions, checking certificate requests for certificate templates that allow the subject information to be specified by the enrollee against a defined policy. If any of the requested Subject string or Subject Alternative Name (SAN) violates the defined rules, the certificate request automatically gets denied by the certification authority. This concept is also known as applying "name constraints" to certificates. The module therefore helps you to tame your certs!

== Value Proposition

As a PKI operator, it is your responsibility to verify and confirm the enrollee's identity, and ensure he is permitted to request a certificate for the specified identity. As the certificate volume in a typical enterprise is quite high, it is common to automate the task of certificate issuance where possible. Active Directory Certificate Services offers the possibility to identify an enrollee by it's Active Directory identity (meaning the PKI delegates the identification job to AD) and build the certificate content based on this information.

Sadly, there are many cases where this is not possible. In these cases, a certificate request is usually put into pending state so that a certificate manager can review and approve/deny the certificate request. However, this contradicts the goal of automatization. Also, putting such a certificate request into pending state is often not possible due to technical reasons. In these cases, the identification job is delegated entirely to the enrollee, which can lead to serious security issues: Any subject information (e.g. logon identities of administrative accounts in user certificates, or fraudulent web addresses in web server certificates) can be specified which opens a large security gap, waiting to be link:https://www.gradenegger.eu/?p=13269[abused by attackers^].

The TameMyCerts policy module addresses, amongst others, the following use cases:

* Certificate issuance must be delegated to a 3rd party service, for example, Mobile Device Management (MDM) systems like link:https://www.microsoft.com/en-us/security/business/microsoft-endpoint-manager[Microsoft Endpoint Manager (aka InTune)^] or link:https://www.vmware.com/content/vmware/vmware-published-sites/de/products/workspace-one.html.html[VMware AirWatch/Workspace One^], link:https://social.technet.microsoft.com/wiki/contents/articles/9063.active-directory-certificate-services-ad-cs-network-device-enrollment-service-ndes.aspx[Network Device Enrollment Service (NDES)^] deployments or similar use cases that require the certificate template to be configured to have the enrollee supply the subject information with the certificate signing request in combination with direct certificate issuance. Without the module, there is absolutely no control over the issued certificate content.
** The module can also mitigate the problem that certificates may be inconsistent among platforms (e.g. having differing subject information on a mobile phone managed by MDM than on a PC that uses Autoenrollment because of inconsistent configuration settings on the MDM) by enforcing certificate content.
** It is also capable of ensuring that a user or computer account exists in Active Directory matching the requested certificate, and that it is enabled and member (or not) of specific security groups (e.g. this can prevent issuing certificates for administrative accounts via MDM).
* Adding the the newly introduced Security Identifier (szOID_NTDS_CA_SECURITY_EXT with object id 1.3.6.1.4.1.311.25.2 that was introduced with link:https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16[KB5014754^]) extension into offline certificate requests, which e.g. allows you to use Microsoft Network Policy Server (NPS) with certificates issued to mobile devices and the like and avoid breaking authentication when "strong" certificate mapping link:https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16#bkmk_fullenforcemode[will be enforced by Microsoft on May 9, 2023^].
* Technical or legal requirements to allow any kind of subject RDN to be enabled for issuance on the certification authority (enabling link:https://www.gradenegger.eu/?p=952[CRLF_REBUILD_MODIFIED_SUBJECT_ONLY^] flag on the certification authority). Without the module, there is no control over which exact subject RDNs are allowed to be issued.
* Certificate templates configured to allow Elliptic Curve Cryptography (ECC) keys. Without the module, it would be possible that certificates get issued that use small RSA keys (e.g. 512 bit or even smaller) even though these would be not allowed in the certificate template configuration, as the Windows Default policy module link:https://www.gradenegger.eu/?p=14138[only validates the key length but not the key algorithm^].
* Issuance of certificates with a validity period within exactly defined timeframe (e.g. valid only exactly for one work shift), or having the requirement to have all certificates end by a specific date.
* Preventing Users to request certificates from templates that are intended to be used solely with link:https://www.gradenegger.eu/?p=2789[AutoEnrollment^] via alternative methods (e.g. MMC.exe).
* It is also the perfect companion for the link:https://github.com/Sleepw4lker/AdcsToRest[AdcsToRest^] REST API for AD CS.

=== Conclusion

The TameMyCerts policy module allows fine-granular control about certificate content to greatly reduce attack surface, as well as ensuring that requested certificates conform to the organization's certificate policies.

== Installing the module

=== Supported Operating Systems and Prerequisites

The module was successfully tested and is supported with the following operating systems:

* Windows Server 2022
* Windows Server 2019
* Windows Server 2016
* Windows Server 2012 R2

Older operating systems are not supported.

For Windows Server 2016 and below, link:https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-7-2-offline-installer-for-windows-05a72734-2127-a15d-50cf-daf56d5faec2[.NET Framework 4.7.2^] must be installed.

=== Installation

To install the module, first create a directory on the certification authority where you intend to store the policy definition files. Then run *install.ps1* as Administrator. You must specify the *-PolicyDirectory* Parameter which specifies the local path for the XML config files you define for each certificate template.

Example:

....
.\Install.ps1 -PolicyDirectory C:\PKIDATA\Policy
....

NOTE: The install script restarts the certification authority service during installation and uninstallation.

NOTE: As the policy module daisy-chains the Windows default policy module, it also uses all of it's registry settings. Therefore, the install script copies this data from the Windows Default module's Registry key to a new one for the TameMyCerts policy module. Each change you perform with certutil commands that would configure the Windows Default policy module is now written to the TameMyCerts policy module's Registry key. If you should decide to uninstall it later on, the settings get copied back so that they stay consistent.

NOTE: Do not install the module on a standalone certification authority. Only install it on certification authorities that are integrated into Active Directory (Enterprise CA).

WARNING: Always create a backup before applying any change to the certification authority configuration.

The script will register the module, create the required registry values and configure the policy module as the active one for the certification authority.

=== Uninstalling

To uninstall the module, run *install.ps1* as Administrator. You must specify the *-Uninstall* parameter.

Example:

....
.\Install.ps1 -Uninstall
....

The script will unregister the module, copy the registry settings back and configure the Windows Default policy module as the active one.

== Configuring the module

Create a policy file in XML format for each certificate template you want to apply a policy for in the folder you specified during installation. Name the file exactly as the certificate template ("cn" LDAP attribute) that shall get examined.

See the supplied sample policy files for an example:

* link:TameMyCerts/Sample_Offline_Computer_SidExtension.xml[Sample_Offline_Computer_SidExtension.xml]
* link:TameMyCerts/Sample_Offline_User.xml[Sample_Offline_User.xml]
* link:TameMyCerts/Sample_Offline_User_SidExtension.xml[Sample_Offline_User_SidExtension.xml]
* link:TameMyCerts/Sample_Offline_User_TPM.xml[Sample_Offline_User_TPM.xml]
* link:TameMyCerts/Sample_Offline_Webserver.xml[Sample_Offline_Webserver.xml]
* link:TameMyCerts/Sample_Online_User_NotAfter.xml[Sample_Online_User_NotAfter.xml]

NOTE: The policy files get loaded when a certificate request gets processed, therefore it is *not* needed to restart the certification authority service after a policy file has been created or changed.

NOTE: We distinguish between certificate requests for certificate templates that are configured to build the subject information from Active directory (called "online" requests) and for such that are configured to have the enrollee supply the subject information with the requests (called "offline" requests). Some of the below settings apply only to offline requests and will have no effect when configured for offline certificate templates.

=== General settings

|===
|Parameter |Mandatory | Description

|AuditOnly
|no
|Audit Mode. No certificate requests get denied but a message will get written into the Event Log when a certificate request violates the given policy. Helps sharpening the policy rules before applying  a policy onto a productive system. Defaults to false.

|NotAfter
|no
|Allows to specify a specific expiration date for all certificates issued for a certificate template. This can be useful in situations where all certificates shall expire after a project ends, or when phasing out weak key sizes to a given date. Must specify in link:https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier[ISO 8601^] compatible format, e.g. "2022-12-31T23:59:59.0000000+01:00".

|AllowedProcesses
|no
|Contains a list of one or more process names that are permitted to get a certificate issued. For example, if you would like to restrict certificate enrollment for a certificate template to Autoenrollment only, you would permit "taskhostw.exe".

|DisallowedProcesses
|no
|Contains a list of one or more process names that are disallowed to get a certificate issued. For 
example, if you would like to deny certificate enrollment via certreq.exe, you could enter it here.

|AllowedCryptoProviders
|no
|Contains a list of one or more Cryptographic Service Provider (CSP) or Key Storage Provider (KSP) names that are permitted for the creation of the certificate request's private key. For example, you could configure a certificate template to use the machine's Trusted Platform Module (TPM) by specifying the Microsoft Platform Crypto Provider and a fallback to the Microsoft Software Key Storage Provider, whereas the policy would only permit requests for the Microsoft Platform Crypto Provider to be issued. This way, you could identify machines where the TPM is in a nonfunctional state by evaluating denied certificate requests. 

|DisallowedCryptoProviders
|no
|Contains a list of one or more Cryptographic Service Provider (CSP) or Key Storage Provider (KSP) names that are disallowed for the creation of the certificate request's private key.

|SecurityIdentifierExtension
|no
|Decides how to handle the Security Identifier certificate extension. If configured to "Deny" (default), the policy module will deny certificate requests containing this extension. If configured to "Add", it will add the objectSid attribute from the Active Directory user or computer account that maps to the certificate (requires directory services mapping to be configured, see below). If it is configured to "Add" and the certificate request already contains Security Identifier certificate extension, it will be overwritten by the policy module.

|===

NOTE: Please be aware that only certificate requests that have been made with the Microsoft API (e.g. Autoenrollment, MMC, certreq, link:https://www.powershellgallery.com/packages/PSCertificateEnrollment[PSCertificateEnrollment^] and similar apps) will contain information about the process and provider that were used to create the certificate request.

=== Configuring rules for the private key

NOTE: The definition and enforcement of rules for the private key is only possible for "offline" certificate templates.

You can specify the following parameters for the private key:

|===
|Parameter |Mandatory |Description

|KeyAlgorithm
|no
|Specifies the key algorithm the certificate request must use. At the moment, this can be "RSA" or "ECC" (which covers both ECDH and ECDSA). Defaults to "RSA".

|MinimumKeyLength
|no
|Specifies the minimum key length the certificate request must use. Defaults to "0" (any key size is allowed). Note that though the Windows Default policy module also verifies this, this may become handy in a migration scenario where you publish the same template both on the old and new certification authority and plan to increase key size when switching to the new one whilst keeping the productive system unchanged.

|MaximumKeyLength
|no
|Specifies the maximum key length the certificate request can use. Defaults to "0" (any key size is allowed).

|===

=== Configuring rules for subject relative distinguished names (RDNs)

NOTE: The definition and enforcement of rules for subject and subject alternative names is only possible for "offline" certificate templates.

Rules for subject RDNs get specified within a "SubjectRule" node under "Subject" section.

NOTE: Any subject RDN that is not defined is considered forbidden and will result in any certificate request containing it getting denied.

A "SubjectRule" can/must contain the following nodes:

|===
|Parameter |Mandatory |Description

|Field
|*yes*
|Specifies the type of the field. See the below list for possible values. *Please be aware that this field is case-sensitive.*

|Mandatory
|no
|Specifies if this field *must* (true) or *may* (false) appear in the certificate request presented. Defaults to "false".

|MaxOccurrences
|no
|Specifies how often this field may appear within a certificate request. Should always be 1 for must subject RDN types. Defaults to 1.

|MinLength
|no
|Specifies the minimum amount of characters the field must contain, to avoid empty RDNs being requested. Defaults to 1. Note that you also can define minimum lengths for parts or the entire field content via regular expressions in the Patterns directive.

|MaxLength
|no
|Specifies the maximum amount of characters the field may contain. Defaults to 128. Note that link:https://www.gradenegger.eu/?p=2717[there is also an upper limit set by the certification authority^]. Also note that you also can define maximum lengths for parts or the entire field content via regular expressions in the Patterns directive.

|Patterns
|*yes*
|For any field type you can define one or more "Pattern" directives describing expressions of which the requested field content must match at least one of to get either permitted or denied. The node is required, so if you would want to allow any content, simply configure a Pattern directive with "^.*$" as expression.

|===

The "Pattern" Parameter is defined as follows:

|===
|Parameter |Mandatory |Description

|Expression
|*yes*
|Specifies the expression the field gets matched against.

|TreatAs
|no
|Specifies how the expression is to be interpreted by TameMyCerts. Supported values are "RegEx" for a regular expression (the default) or "Cidr" to match against an IP subnet in CIDR notation (e.g. 192.168.0.0/16). To allow any IP Address, specify 0.0.0.0/0.

|Action
|no
|Specifies if a match for the pattern will "Allow" the certificate to get issued (the default) or "Deny" the certificate request.

|===

To define a policy for one or more subject Relative Distinguished Name (RDN) types, adjust the "field" to one of the following (as defined in link:https://www.itu.int/itu-t/recommendations/rec.aspx?rec=X.520[ITU-T X.520^] and link:https://datatracker.ietf.org/doc/html/rfc4519#section-2[RFC 4519^]).

NOTE: Each RDN type can only be defined once in a policy definition file!

The following RDN types are enabled/allowed by default on AD CS:

* countryName
* commonName
* domainComponent
* emailAddress
* organizationName
* organizationalUnitName
* localityName
* stateOrProvinceName

The following RDNs can additionally be defined but must also explicitly be enabled in the certification authority configuration (by modifying the link:https://www.gradenegger.eu/?p=10183[SubjectTemplate^] Registry value):

* givenName
* initials
* surname
* streetAddress
* title
* unstructuredName
* unstructuredAddress
* deviceSerialNumber

It is also possible to enable any kind of RDNs in AD CS if the link:https://www.gradenegger.eu/?p=952[CRLF_REBUILD_MODIFIED_SUBJECT_ONLY^] flag is enabled. This should enable the following:

* postalCode
* description
* postOfficeBox
* telephoneNumber
* any "unknown" (not identified by one of the above names) RDN can be specified by using it's object identifier. The OID must be specified with an "OID." prefix, e.g. "OID.1.2.3.4.5".

NOTE: Usually, it is recommended to avoid enabling the link:https://www.gradenegger.eu/?p=952[CRLF_REBUILD_MODIFIED_SUBJECT_ONLY^] flag, but when using this policy module, it should be fine as it allows fine-grained control about which RDN types are allowed and which not.

NOTE: Please be aware that the SubjectTemplate value of the CA uses a different syntax for field type names.

=== Configuring rules for Subject Alternative Names

Rules for subject RDNs get specified within a "SubjectRule" node under "Subject" section.

The "SubjectRule" configuration is already described above.

To define a policy for one or more subject alternative name (SAN) type, adjust the "field" to one of the following (as defined in link:https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.6[RFC 5280^] with the exception of the (Microsoft-)proprietary userPrincipalName).

* dNSName
* iPAddress
* userPrincipalName
* rfc822Name
* uniformResourceIdentifier

NOTE: Other SAN types are currently not implemented (yet). However, the ones that are currently implemented should be sufficient for the majority of use cases.

== Configuring rules for Directory Services Mapping

Rules for Directory Mapping get specified within a "DirectoryServicesMapping" node.

|===
|Parameter |Mandatory |Description

|CertificateAttribute
|no
|The field which is taken from the certificate request as the identity to map to a corresponding Active Directory object. May contain any identity that is listed above for either the Subject Distinguished Name, or for the Subject Alternative Name. Defaults to "userPrincipalName".

|DirectoryServicesAttribute
|no
|The attribute of the Active Directory object that must match the certificate attribute. May be "cn", "name", "sAMAccountName", "userPrincipalName" or "dNSHostName". Defaults to "userPrincipalName".

|ObjectCategory
|no
|The categopry of the Active Directory object to be searched for. May be "computer" or "user". Defaults to "user".

|SearchRoot
|no
|The distinguished name of the LDAP path the search for the Active Directory object shall start from. Defaults to using the global catalog for the entire forest.

|AllowedSecurityGroups
|no
|A list of distinguished names of security groups the account must be member of (at least one of them).

|DisallowedSecurityGroups
|no
|A list of distinguished names of security groups the account must *not* be member of (at least one of them).

|===

NOTE: Please be aware that it is currently *not* possible to use the Primary Group of an AD object (Domain Users, Domain Guests, Domain Computers, Domain Controllers) for filtering.

== Monitoring and Troubleshooting

If a certificate request violates the defined policy, the certification authority will deny it with one of the below error codes and messages. It will log link:https://www.gradenegger.eu/?p=8544[Event with ID 53^]. The error code/message will also be handed over to the requesting client over the DCOM protocol as answer to the certificate request.

The following error codes can be thrown by the policy module when a request was denied:

|===
|Message |Symbol |Description

|The permissions on the certificate template do not allow the current user to enroll for this type of certificate.
|CERTSRV_E_TEMPLATE_DENIED
|Occurs if the process used to create the certificate request is unknown, not allowed or explicitly disallowed.

|The certificate has an invalid name. The name is not included in the permitted list or is explicitly excluded.
|CERT_E_INVALID_NAME
|Occurs if the request's subject oder subject alternative name violates the defined rules.

|The public key does not meet the minimum size required by the specified certificate template.
|CERTSRV_E_KEY_LENGTH
|Occurs if the request's public key violates the defined rules for key algorithm or maximum key length.

|The request subject name is invalid or too long.
|CERTSRV_E_BAD_REQUESTSUBJECT
|Occurs if the request's subject string cannot be interpreted by the policy module.

|An internal error occurred.
|ERROR_INVALID_DATA
|Occurs if the policy module is unable to interpret the given policy file.

|The specified time is invalid.
|ERROR_INVALID_TIME
|Occurs if an invalid date was requested for the "StartDate" certificate request attribute.

|===

WARNING: Please be aware that if no policy file exists for a given certificate template, the request gets accepted as this would be the original behavior of the Windows Default policy module.

=== Logs

In addition to the certification authorities regular log entries, the policy module will also write a detailed log entry if a certificate request was denied due to a policy violation or failure. Find the logs under the "Application" Event Log with the "TameMyCerts" Event Source.

|===
|ID |Type |Description

|1
|Information
|Occurs if the Windows Default policy was successfully loaded and TameMyCerts is ready to process incoming requests. Occurs only if the certification authority's "LogLevel" is set to 4 or higher.

|2
|Error
|Occurs if the Windows Default policy was *not* successfully loaded (link:https://docs.microsoft.com/en-us/windows/win32/api/certpol/nf-certpol-icertpolicy-initialize[Initialize^] method failed). Will cause the CA service to not start.

|3
|Error
|Occurs if the Windows Default policy throws an exception on the link:https://docs.microsoft.com/en-us/windows/win32/api/certpol/nf-certpol-icertpolicy-verifyrequest[VerifyRequest^] method (the certificate request gets denied in this case).

|4
|Error
|Occurs if the Windows Default policy was *not* successfully unloaded (link:https://docs.microsoft.com/en-us/windows/win32/api/certpol/nf-certpol-icertpolicy-shutdown[ShutDown^] method failed.).

|5
|Warning
|Occurs if AuditOnly is enabled for a certificate template and a certificate request would get denied because of a policy violation. Contains a detailed information which kind of policy violation caused the request to get denied.

|6
|Warning
|Occurs if a certificate request was denied because of a policy violation. Contains a detailed information which kind of policy violation caused the request to get denied. Note that the information about which client requestd the certificate can be obtained via link:https://www.gradenegger.eu/?p=8643[audit event 4886^].

|7
|Warning
|Occurs if there is no policy configuration file defined for the certificate template used certificate request. The certificate request gets allowed in this case.

|8
|Error
|Occurs if the TameMyCerts policy module was unable to determine information about the request's certificate template from either the CA or the Active Directory.

|9
|Error
|Occurs it the TameMyCerts policy module is loaded on a standalone certification authority, which is unsupported at the moment. Will cause the CA service to not start.

|10
|Error
|Occurs if a certificate request was denied because because the policy file for the certificate template could not be interpreted.

|11
|Information
|Occurs if the Windows Default policy module denied a certificate request, thus the additional logic of TameMyCerts was not triggered at all for the given request. Occurs only if the certification authority's "LogLevel" is set to 4 or higher.

|12
|Error
|Occurs if the certification authority has the (link:https://www.gradenegger.eu/?p=1486[proven insecure^]) EDITF_ATTRIBUTESUBJECTALTNAME2 flag set, and a request containing the "san" attribute was passed. The policy module will deny such requests. You should consider triggering an alarm when this happens.

|13
|Information
|Occurs if the expiration date of a certificate was capped because of policy configuration (NotAfter parameter). Occurs only if the certification authority's "LogLevel" is set to 4 or higher.

|===

=== Issuing Certificates with an exactly defined validity period

The Windows Default policy module link:https://www.gradenegger.eu/?p=6502[allows to specify the exact expiration date^] (NotAfter) for a certificate by specifying an "ExpirationDate" attribute whilst submitting the certificate request. TameMyCerts adds support for a "StartDate" attribute which does the exact same for the begin of the certificate's validity period (NotBefore).

To enable the feature, you must enable the EDITF_ATTRIBUTEENDDATE flag in the policy module of the certification authority and restart the certification authority service afterwards.

....
certutil -setreg Policy\Editflags +EDITF_ATTRIBUTEENDDATE
net stop certsvc
net start certsvc
....

Afterwards, you both can specify *StartDate* and *ExpirationDate* in link:https://datatracker.ietf.org/doc/html/rfc2616[RFC 2616^] compliant form whilst submitting the certificate request.

Example:

....
certreq ^
-config "ca02.intra.adcslabor.de\ADCS Labor Issuing CA 1" ^
-attrib "CertificateTemplate:ADCSLaborWebServer\nStartDate:Tue, 1 Mar 2022 08:00:00 GMT\nExpirationDate:Tue, 1 Mar 2022 16:00:00 GMT" ^
-submit "SomeWebServer.req"
....

NOTE: When an invalid date is being requested, the certificate request will get denied with ERROR_INVALID_TIME.

NOTE: TameMyCerts currently only supports specifying "StartDate" whilst submitting the certificate request but not as custom request attributes. The alternative method of specifying "ValidityPeriod" and "ValidityPeriodUnits" for the expiration date can currently not be used in combination with the "StartDate" attribute as it gets applied afterwards and thus won't deliver the expected result.

== Building

If you just want to install and use TameMyCerts, there is no need for building from source. Please download the binary package from the link:https://github.com/Sleepw4lker/TameMyCerts/releases[releases page] in this case.

If you want to build the module from source, call the supplied build scripts from the Visual Studio Developer command prompt:

* link:TameMyCerts/make_debug.cmd[make_debug.cmd] for a debug build (does not increment version bumber).
* link:TameMyCerts/make_release.cmd[make_release.cmd] for a release build (auto-increments version number).