== Configuring Directory Services mapping

NOTE: Applies to *online* and *offline* certificate templates.

Directory Services mapping allows you to map an identity in a certificate request back to an Active Directory object. This way, a variety of policies can be applied, containing:

* Verify that there is a user or computer object to which the certificate request belongs.
* Verify that the object is not disabled.
* Verify that the object is located in a specific Organizational Unit (OU).
* Verify that the object is member of a specific security group.
* Verify that the object is *not* member of a specific security group.
* Enable features like supplementing the link:sid-extension.adoc[Security Identifier (SID) certificate extension] or link:modify-subject-dn.adoc[Modifying the Subject Distinguished Name (DN)].

=== Configuring

Rules for Directory Mapping get specified within the *DirectoryServicesMapping* node.

Example (enabling the mapping with default values for user objects in an offline template and for both types in online templates):

NOTE: When using an online certificate template, the object category as well as certificate and directory services attributes are determined automatically.

....
<DirectoryServicesMapping />
....

Example (enabling the mapping with default values for computer objects in an offline template):
....
<DirectoryServicesMapping>
  <CertificateAttribute>dNSName</CertificateAttribute>
  <DirectoryServicesAttribute>dNSHostName</DirectoryServicesAttribute>
  <ObjectCategory>computer</ObjectCategory>
</DirectoryServicesMapping>
....

|===
|Parameter |Mandatory |Description

|CertificateAttribute
|no
|The field which is taken from the certificate request as the identity to map to a corresponding Active Directory object. May contain any identity that is listed above for either the Subject Distinguished Name, or for the Subject Alternative Name. Defaults to "userPrincipalName".

|DirectoryServicesAttribute
|no
|The attribute of the Active Directory object that must match the certificate attribute. May be _"cn"_, _"name"_, _"sAMAccountName"_, _"userPrincipalName"_ or _"dNSHostName"_. Defaults to _"userPrincipalName"_.

|ObjectCategory
|no
|The category of the Active Directory object to be searched for. May be "computer" or "user". Defaults to "user".

|SearchRoot
|no
|The distinguished name of the LDAP path the search for the Active Directory object shall start from. Defaults to using the global catalog for the entire forest.

|AllowedSecurityGroups
|no
|A list of distinguished names of security groups the account must be member of (at least one of them).

|DisallowedSecurityGroups
|no
|A list of distinguished names of security groups the account must *not* be member of (at least one of them).

|PermitDisabledAccounts
|no
|Permits certificates to get issued even if the Active Directory object is disabled.

|SubjectDistinguishedName
|no
|Allows adding attributes of the Active Directory object into the Subject Distinguished Name (DN) of the issued certificate. See link:modify-subject-dn.adoc[Modifying the Subject Distinguished Name (DN)].

|===

NOTE: Please be aware that the _cn_, _name and _sAMAccountName_ attributes are only unique per Domain, but not on Forest level. TameMyCerts denies a certificate request if more than one account with the same identifier is found.

NOTE: Please be aware that the _userPrincipalName_ attribute may not be populated in all scenarios.

NOTE: Please be aware that it is currently *not* possible to use the Primary Group of an AD object (Domain Users, Domain Guests, Domain Computers, Domain Controllers) for filtering.

NOTE: Please be aware that the certification authority needs LDAP access to all Domain Controllers that are involved in the DS mapping process. Also, LDAP GC (Global Catalog) access is required as well when SearchRoot is not explicitly specified. Consult the official link:https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/config-firewall-for-ad-domains-and-trusts[Microsoft documentation^] for further information.

=== See also
* link:sid-extension.adoc[Working with the Security Identifier (SID) certificate extension]
* link:modify-subject-dn.adoc[Modifying the Subject Distinguished Name (DN)]

link:index.adoc[Back to Start]