== Configuring a fixed expiration date for all issued certificates

NOTE: Applies to *online* and *offline* certificate templates.

TameMyCerts allows to configure certificates issued for a specific certificate template to expire at an exactly configured point in time. This can be useful in scenarios where you want to ensure that e.g. certificates with weak keys get phased out until a specified point in time.

The behavior is as follows:

* If the configured expiration date is more than the regular certificate expiration date as configured in the certificate template (or certificate authority), no change is done to the issued certificate.
* If the configured expiration date has not yet passed but is less than the regular expiration date as configured in the certificate template (or certifificate authority), the expiration date is set to the configured point in time.
* If the configured expiration date has passed, certificate requests get denied.

=== Configuration

You configure the expiration date with the *NotAfter* directive in your policy configuration file.

The time gets specified as an ISO 8601 compliant string in the syntax of "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffzzz". See link:https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings[here^] for further explanation.

Example (all certificates expire on Dec 31, 2022 23:59:59 Europe/Berlin (UTC+1) time):

....
<NotAfter>2022-12-31T23:59:59.0000000+01:00</NotAfter>
....

=== See also
* link:configuring.adoc[Configuring the TameMyCerts policy module]

link:index.adoc[Back to Start]